EXO1
USE webDevelopment
CREATE TABLE `languages`(
  `id` INT() UNSIGNED NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(40) NOT NULL,
  CONSTRAINT PK _id PRIMARY KEY (`id`)
)
ENGINE=INNODB;

EXO2
CREATE TABLE IF NOT EXISTS `tools`(
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tool` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=INNODB;

EXO3
CREATE TABLE `frameworks`(
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=INNODB;

EXO4
CREATE TABLE `libraries`(
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `library` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`)
)
ENGINE=INNODB;

EXO5
CREATE TABLE IF NOT EXISTS `ide`(
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idename` VARCHAR(40) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE=INNODB;

EXO6
CREATE TABLE IF NOT EXISTS `frameworks`(
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE=INNODB;

EXO7
DROP TABLE IF EXISTS `tools`;

EXO8
DROP TABLE IF EXISTS `libraries`;

EXO9
DROP TABLE IF EXISTS `ide`;

TP
CREATE DATABASE IF NOT EXISTS `codex` CHARACTER SET "UTF8";
CREATE TABLE IF NOT EXISTS `clients`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(40) NOT NULL,
  `firstname` VARCHAR(40) NOT NULL,
  `birthDate` DATETIME NOT NULL,
  `address`VARCHAR(40) NOT NULL,
  `firstPhoneNumber` SMALLINT UNSIGNED NOT NULL,
  `secondPhoneNumber`SMALLINT UNSIGNED NOT NULL,
  `mail` VARCHAR(40) NOT NULL,
  CONSTRAINT Pk_id PRIMARY KEY(id)
)
ENGINE=INNODB;
